### ISSUE TITLE
engineGetDigestLength() missing from WolfCryptMessageDigest classes

### ISSUE THREAD

**Issue by ErikBergfurInfor** [wolfSSL/wolfcrypt-jni#26]
In the Java 17 environment I'm trying to get running, I noticed that the ciphers touched are dependant on the `MessageDigestSpi::engineGetDigestLength()` to return a non-zero value for the MessageDigest-classes.
By creating an override in WolfCryptMessageDigestSha256, for instance, and return the value of `this.sha.digestSize()`, the crypto-code happily continues without a dive-by-zero exception.

**Comment by cconlon** [comment]
Hi @ErikBergfurInfor, thanks for the reports.  I'll be looking into this and the other issues you recently opened.

**Comment by ErikBergfurInfor** [comment]
I tested the patch with the latest wolfssl-5.1.1-gplv3-fips-ready.zip in my amazon corretto 17 environment and this error doesn't occur any more
